language: java
dist: bionic
jdk:
  - oraclejdk11

env:
  global: ORG_GRADLE_PROJECT_downloadIdeaSources=false
  matrix:
    - ORG_GRADLE_PROJECT_ideaVersion=LATEST-EAP-SNAPSHOT ORG_GRADLE_PROJECT_grammarKitVersion=2019.3
    - ORG_GRADLE_PROJECT_ideaVersion=2020.1 ORG_GRADLE_PROJECT_grammarKitVersion=2019.3
    - ORG_GRADLE_PROJECT_ideaVersion=2019.3.4 ORG_GRADLE_PROJECT_grammarKitVersion=2019.3

matrix:
  allow_failures:
    - env: ORG_GRADLE_PROJECT_ideaVersion=LATEST-EAP-SNAPSHOT ORG_GRADLE_PROJECT_grammarKitVersion=2019.3
  fast_finish: true

install: true

script:
  # BACKCOMPAT:
  # HACK: Force grammar kit to use current IDEA version when generating parser.
  # For actual compilation and running the version from the matrix will be used.
  - ORG_GRADLE_PROJECT_ideaVersion=2020.1 ORG_GRADLE_PROJECT_grammarKitVersion=2019.3 ./gradlew generateFusionParser
  - ./gradlew check -x generateFusionParser

# https://docs.travis-ci.com/user/languages/java/#Caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -fr $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
  - rm -fr $HOME/.gradle/caches/*/fileHashes/fileHashes.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
